require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe KalibroRangesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # KalibroRange. As you add validations to KalibroRange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KalibroRangesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "POST create" do
    pending
    describe "with valid params" do
      it "creates a new KalibroRange" do
        expect {
          post :create, {:kalibro_range => valid_attributes}, valid_session
        }.to change(KalibroRange, :count).by(1)
      end

      it "assigns a newly created kalibro_range as @kalibro_range" do
        post :create, {:kalibro_range => valid_attributes}, valid_session
        expect(assigns(:kalibro_range)).to be_a(KalibroRange)
        expect(assigns(:kalibro_range)).to be_persisted
      end

      it "redirects to the created kalibro_range" do
        post :create, {:kalibro_range => valid_attributes}, valid_session
        expect(response).to redirect_to(KalibroRange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kalibro_range as @kalibro_range" do
        post :create, {:kalibro_range => invalid_attributes}, valid_session
        expect(assigns(:kalibro_range)).to be_a_new(KalibroRange)
      end

      it "re-renders the 'new' template" do
        post :create, {:kalibro_range => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    pending
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kalibro_range" do
        kalibro_range = KalibroRange.create! valid_attributes
        put :update, {:id => kalibro_range.to_param, :kalibro_range => new_attributes}, valid_session
        kalibro_range.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested kalibro_range as @kalibro_range" do
        kalibro_range = KalibroRange.create! valid_attributes
        put :update, {:id => kalibro_range.to_param, :kalibro_range => valid_attributes}, valid_session
        expect(assigns(:kalibro_range)).to eq(kalibro_range)
      end

      it "redirects to the kalibro_range" do
        kalibro_range = KalibroRange.create! valid_attributes
        put :update, {:id => kalibro_range.to_param, :kalibro_range => valid_attributes}, valid_session
        expect(response).to redirect_to(kalibro_range)
      end
    end

    describe "with invalid params" do
      it "assigns the kalibro_range as @kalibro_range" do
        kalibro_range = KalibroRange.create! valid_attributes
        put :update, {:id => kalibro_range.to_param, :kalibro_range => invalid_attributes}, valid_session
        expect(assigns(:kalibro_range)).to eq(kalibro_range)
      end

      it "re-renders the 'edit' template" do
        kalibro_range = KalibroRange.create! valid_attributes
        put :update, {:id => kalibro_range.to_param, :kalibro_range => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    pending
    it "destroys the requested kalibro_range" do
      kalibro_range = KalibroRange.create! valid_attributes
      expect {
        delete :destroy, {:id => kalibro_range.to_param}, valid_session
      }.to change(KalibroRange, :count).by(-1)
    end

    it "redirects to the kalibro_ranges list" do
      kalibro_range = KalibroRange.create! valid_attributes
      delete :destroy, {:id => kalibro_range.to_param}, valid_session
      expect(response).to redirect_to(kalibro_ranges_url)
    end
  end

end
