require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MezuroRangesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # MezuroRange. As you add validations to MezuroRange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MezuroRangesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mezuro_ranges as @mezuro_ranges" do
      mezuro_range = MezuroRange.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:mezuro_ranges)).to eq([mezuro_range])
    end
  end

  describe "GET show" do
    it "assigns the requested mezuro_range as @mezuro_range" do
      mezuro_range = MezuroRange.create! valid_attributes
      get :show, {:id => mezuro_range.to_param}, valid_session
      expect(assigns(:mezuro_range)).to eq(mezuro_range)
    end
  end

  describe "GET new" do
    it "assigns a new mezuro_range as @mezuro_range" do
      get :new, {}, valid_session
      expect(assigns(:mezuro_range)).to be_a_new(MezuroRange)
    end
  end

  describe "GET edit" do
    it "assigns the requested mezuro_range as @mezuro_range" do
      mezuro_range = MezuroRange.create! valid_attributes
      get :edit, {:id => mezuro_range.to_param}, valid_session
      expect(assigns(:mezuro_range)).to eq(mezuro_range)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MezuroRange" do
        expect {
          post :create, {:mezuro_range => valid_attributes}, valid_session
        }.to change(MezuroRange, :count).by(1)
      end

      it "assigns a newly created mezuro_range as @mezuro_range" do
        post :create, {:mezuro_range => valid_attributes}, valid_session
        expect(assigns(:mezuro_range)).to be_a(MezuroRange)
        expect(assigns(:mezuro_range)).to be_persisted
      end

      it "redirects to the created mezuro_range" do
        post :create, {:mezuro_range => valid_attributes}, valid_session
        expect(response).to redirect_to(MezuroRange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mezuro_range as @mezuro_range" do
        post :create, {:mezuro_range => invalid_attributes}, valid_session
        expect(assigns(:mezuro_range)).to be_a_new(MezuroRange)
      end

      it "re-renders the 'new' template" do
        post :create, {:mezuro_range => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mezuro_range" do
        mezuro_range = MezuroRange.create! valid_attributes
        put :update, {:id => mezuro_range.to_param, :mezuro_range => new_attributes}, valid_session
        mezuro_range.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested mezuro_range as @mezuro_range" do
        mezuro_range = MezuroRange.create! valid_attributes
        put :update, {:id => mezuro_range.to_param, :mezuro_range => valid_attributes}, valid_session
        expect(assigns(:mezuro_range)).to eq(mezuro_range)
      end

      it "redirects to the mezuro_range" do
        mezuro_range = MezuroRange.create! valid_attributes
        put :update, {:id => mezuro_range.to_param, :mezuro_range => valid_attributes}, valid_session
        expect(response).to redirect_to(mezuro_range)
      end
    end

    describe "with invalid params" do
      it "assigns the mezuro_range as @mezuro_range" do
        mezuro_range = MezuroRange.create! valid_attributes
        put :update, {:id => mezuro_range.to_param, :mezuro_range => invalid_attributes}, valid_session
        expect(assigns(:mezuro_range)).to eq(mezuro_range)
      end

      it "re-renders the 'edit' template" do
        mezuro_range = MezuroRange.create! valid_attributes
        put :update, {:id => mezuro_range.to_param, :mezuro_range => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mezuro_range" do
      mezuro_range = MezuroRange.create! valid_attributes
      expect {
        delete :destroy, {:id => mezuro_range.to_param}, valid_session
      }.to change(MezuroRange, :count).by(-1)
    end

    it "redirects to the mezuro_ranges list" do
      mezuro_range = MezuroRange.create! valid_attributes
      delete :destroy, {:id => mezuro_range.to_param}, valid_session
      expect(response).to redirect_to(mezuro_ranges_url)
    end
  end

end
